name = "auto-shorts-cf"
main = "index.ts"               # âœ… Ildizdagi index.ts
compatibility_date = "2024-12-08"

# KV
[[kv_namespaces]]
binding = "VIDEO_QUEUE"
id = "58d50a7063994480abcc1ec0705cbd28"  # keyin to'ldirasiz

# Cron
[[triggers]]
cron = "0 */2 * * *"

# Environment Variables
[vars]
CLOUDINARY_CLOUD_NAME = "dazj3ppjl"
CLOUDINARY_UPLOAD_PRESET = "auto_shorts_preset"
GROQ_API_KEY = "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"
TECH_BUNI_YT_TOKEN = "1//04UeU7EyoCu8CCgYIARAAGAQSNWF-L9Ir00Mr1FNIfzry4tRcLW_43TfAMPRHLgwbkCyDfyaZ_oLMmv97aSctVA epQbWHt44m-jw"
# ... barcha tokenlar
