name = "auto-shorts-cf"
main = "index.ts"
compatibility_date = "2024-12-08"

# KV
kv_namespaces = [
  { binding = "VIDEO_QUEUE", id = "58d50a7063994480abcc1ec0705cbd28" }
]

# Cron (har 2 soatda)
triggers = [
  { cron = "0 */2 * * *" }
]

# Environment Variables
[vars]
CLOUDINARY_CLOUD_NAME = "daq8wfgnt"
CLOUDINARY_UPLOAD_PRESET = "ml_default"
GROQ_API_KEY = "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"
TECH_BUNI_YT_TOKEN = "1//04UeU7EyoCu8CCgYIARAAGAQSNWF-L9Ir00Mr1FNIfzry4tRcLW_43TfAMPRHLgwbkCyDfyaZ_oLMmv97aSctVAepQbWHt44m-jw"
# ... barcha tokenlar
